function heartAttackDataset = importDataset(filename, dataLines)
%importDataset Import data from a text file
%  HEART = importDataset(FILENAME) reads data from text file FILENAME for
%  the default selection.  Returns the data as a table.
%
%  HEART = importDataset(FILE, DATALINES) reads data for the specified row
%  interval(s) of text file FILENAME. Specify DATALINES as a positive
%  scalar integer or a N-by-2 array of positive scalar integers for
%  dis-contiguous row intervals.
%
%  Example:
%  heart = importDataset("...\Heart Attack Prediction Study\Dataset\heart.csv", [2, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 28-Aug-2023 17:37:04

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [2, Inf];
end

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 14);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Age", "Sex", "ChestPainType", "RestingBloodPressure", "Cholesterol", "FastingBloodSugar", "RestingEC", "Thalach", "ExerciseInducedAngina", "STDepression", "SlopePeakExSTSeg", "NumberMajorVessels", "Thalassemia", "Output"];
opts.VariableTypes = ["double", "double", "categorical", "double", "double", "categorical", "categorical", "double", "categorical", "double", "categorical", "categorical", "categorical", "categorical"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
heartAttackDataset = readtable(filename, opts);

end
